(() => {
'use strict';
const $ = s => document.querySelector(s), $$ = s => [...document.querySelectorAll(s)];
const names = {h:'حمودي', z:'زوزا'};
const state = {screen:'menu-screen', round:0, scores:{h:0,z:0}, wins:{h:0,z:0}, bestCombo:0, bestChallenge:'—', sound:true, paused:false, timers:[], raf:null, roundLocked:false, challengeData:{}};
const challengeNames=['أسرع واحد','Tap Rush','الذاكرة','صيد الهدف','لون ولا كلمة؟','الحساب السريع','تفادى العقبات','التوقيت المثالي','اختار كارت','مين يعرف التاني؟','صح ولا غلط','أسرع إجابة','اضغط بالترتيب','Reaction Combo','FINAL BATTLE'];
const tags=['REACTION','TAP RUSH','MEMORY','TARGET HIT','COLOR TRAP','QUICK MATH','DODGE','PERFECT TIMING','LUCKY CARDS','COUPLE QUIZ','TRUE / FALSE','FAST ANSWER','ORDER','COMBO','FINAL BATTLE'];
const questions=['مين فيكم بيصالح التاني أسرع؟','مين بيتخانق أكتر؟','مين بيغير أكتر؟','مين بيحب الدلع أكتر؟','مين بيضحك أسرع؟','مين ممكن ينسى مناسبة؟','مين بيعرف التاني أكتر؟','مين بيتوتر أسرع؟','مين أكثر واحد عناد؟','مين ممكن يقول أنا مش زعلان وهو زعلان؟','مين بيحب الخروجات المفاجئة؟','مين بيختار الفيلم أسرع؟','مين بيصحى من أول منبه؟','مين بيحتفظ بالسر أحسن؟','مين بيعمل نفسه مش سامع؟','مين بيطلب أكل أكتر؟','مين بيبادر بالصلح؟','مين بيحب الصور أكتر؟','مين ممكن يضحك وقت الخناق؟','مين ذاكرته أقوى؟','مين بيخاف من الحشرات؟','مين بيحب المفاجآت؟','مين بياخد وقت أطول عشان يجهز؟','مين كلامه حلو أكتر؟','مين ممكن يغير رأيه في آخر لحظة؟','مين بيفتكر التفاصيل الصغيرة؟','مين بيكسب في النقاش؟','مين بيحب السهر؟','مين بيبدأ الكلام بعد الزعل؟','مين بيحب الهدايا العملية؟','مين بيقول نكت وحشة؟','مين بيرد أسرع على الرسائل؟','مين بيحب البحر؟','مين بيضيع حاجاته أكتر؟','مين بيخطط للمستقبل؟','مين بيهزر وقت الجد؟','مين بيحب القهوة أكتر؟','مين بيتوتر من الانتظار؟','مين بيحب يجرب حاجة جديدة؟','مين بيفهم التلميحات؟','مين بيحلم أكتر؟','مين بيحب يختار الأسماء؟','مين بيكسب في ألعاب السرعة؟','مين بيغار لو التاني اتأخر؟','مين بيعمل مفاجآت ألطف؟','مين بيكمل الأكل بتاع التاني؟','مين صوته أحلى؟','مين بيفتكر أول مقابلة؟','مين بيضحك من قلبه أسرع؟','مين بيعرف يهون على التاني؟','مين ممكن يسافر فجأة؟','مين بيرتب أكتر؟','مين بينام أسرع؟','مين بيحب الكلام الطويل؟','مين بيلاحظ التغيير في المزاج؟','مين أكثر رومانسية؟','مين بيكسب في لعبة تركيز؟'];
let audioCtx;
function tone(type){if(!state.sound)return;try{audioCtx ||= new (window.AudioContext||window.webkitAudioContext)(); if(audioCtx.state==='suspended')audioCtx.resume(); const o=audioCtx.createOscillator(),g=audioCtx.createGain(); const map={click:[300,.05],count:[440,.16],start:[660,.22],correct:[780,.14],wrong:[160,.18],win:[620,.35],score:[920,.12],final:[1040,.45]};const [f,d]=map[type]||map.click;o.frequency.value=f;o.type=type==='wrong'?'sawtooth':'sine';g.gain.setValueAtTime(.001,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.12,audioCtx.currentTime+.01);g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+d);o.connect(g).connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+d+.02)}catch(e){}}
function clearLoops(){state.timers.forEach(clearTimeout);state.timers.forEach(clearInterval);state.timers=[];if(state.raf)cancelAnimationFrame(state.raf);state.raf=null}
function later(fn,ms){const id=setTimeout(()=>{state.timers=state.timers.filter(x=>x!==id);fn()},ms);state.timers.push(id);return id}
function every(fn,ms){const id=setInterval(fn,ms);state.timers.push(id);return id}
function show(id){$$('.screen').forEach(s=>s.classList.remove('active'));$('#'+id).classList.add('active');state.screen=id}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');later(()=>t.classList.remove('show'),1900)}
function updateScore(){ $('#score-h').textContent=state.scores.h;$('#score-z').textContent=state.scores.z;$('#overall-progress').style.width=((state.round+1)/15*100)+'%' }
function setText(sel,text){$(sel).textContent=text}
function start(){tone('click');state.round=0;state.scores={h:0,z:0};state.wins={h:0,z:0};state.bestCombo=0;state.bestChallenge='—';show('setup-screen')}
function countdown(){tone('start');show('countdown-screen');let n=3;setText('#count-number',n);setText('#count-caption','جهزوا صوابعكم!');const id=every(()=>{n--;if(n>0){tone('count');setText('#count-number',n)}else{clearLoops();setText('#count-number','يلا!');setText('#count-caption','مين هيخطف أول نقطة؟');tone('start');later(loadRound,700)}},900)}
function loadRound(){clearLoops();state.roundLocked=false;state.challengeData={};show('game-screen');updateScore();setText('#round-number','التحدي '+String(state.round+1).padStart(2,'0'));setText('#round-kicker',challengeNames[state.round]);setText('#challenge-tag',tags[state.round]);setText('#challenge-title',challengeNames[state.round]);const area=$('#challenge-area');area.innerHTML='';const funcs=[fastest,tapRush,memory,targetHit,colorTrap,quickMath,dodge,perfectTiming,cards,coupleQuiz,trueFalse,fastAnswer,order,combo,finalBattle];funcs[state.round](area)}
function countdownIntro(text,cb){setText('#challenge-instruction',text);const area=$('#challenge-area');area.innerHTML='<div class="intro-count">3</div>';let n=3;const id=every(()=>{n--;if(n>0){area.innerHTML='<div class="intro-count">'+n+'</div>';tone('count')}else{clearLoops();cb()}},650)}
function timer(seconds,onDone,label='الوقت'){let left=seconds;setText('#timer-value',left+'s');setText('#timer-text',label);$('#timer-fill').style.width='100%';const started=performance.now();const id=every(()=>{left--;setText('#timer-value',Math.max(0,left)+'s');if(left<=0){clearLoops();onDone();return}$('#timer-fill').style.width=(left/seconds*100)+'%'},1000);return id}
function finish(winner,points=1,meta={}){if(state.roundLocked)return;state.roundLocked=true;clearLoops();if(winner==='draw'){toast('تعادل الجولة!');}else{state.scores[winner]+=points;state.wins[winner]++;state.bestChallenge=challengeNames[state.round];tone('score')}updateScore();showResult(winner,points,meta)}
function showResult(winner,points,meta){show('result-screen');const medal=$('#result-medal');medal.className='result-medal '+(winner==='z'?'blue':winner==='draw'?'draw':'');setText('#result-medal',winner==='draw'?'=':winner==='z'?'ز':'ح');setText('#result-title',winner==='draw'?'تعادل الجولة!':names[winner]+' كسب'+(winner==='z'?'ت':'')+' الجولة!');setText('#result-subtitle',winner==='draw'?'ولا يهم… الجولة الجاية هتحسمها.':points===2?'دي كانت ضربة معلم… +2 نقطة!':'يا سلام يا نجم… النقطة راحت لك.');setText('#result-points',winner==='draw'?'—':'+'+points);setText('#result-h',state.scores.h);setText('#result-z',state.scores.z);}
function next(){tone('click');if(state.round>=14){finalResult();return}state.round++;loadRound()}
function finalResult(){clearLoops();show('final-screen');const h=state.scores.h,z=state.scores.z;setText('#final-title',h===z?'التعادل!':h>z?'حمودي كسب!':'زوزا كسبت!');setText('#final-subtitle',h===z?'ولا حد يقدر يقول إنه أحسن… انتوا الاتنين أبطال.':'بس الحب كسبان دايمًا.');setText('#final-h',h);setText('#final-z',z);setText('#wins-h',state.wins.h);setText('#wins-z',state.wins.z);setText('#best-challenge',state.bestChallenge);setText('#best-combo',state.bestCombo);tone(h===z?'score':'final')}
function fastest(area){setText('#challenge-instruction','استنى الإشارة… أول واحد يدوس يكسب!');area.innerHTML='<button class="challenge-btn" id="fast-btn">استنى...</button>';const b=$('#fast-btn');let ready=false;b.addEventListener('pointerdown',()=>{tone('click');if(state.roundLocked)return;if(!ready){b.textContent='استعجلت يا نجم!';tone('wrong');finish(state.round%2?'h':'z',0);return}finish(state.round%2?'z':'h')},{once:false});later(()=>{ready=true;b.textContent='دوس دلوقتي!';b.style.background='linear-gradient(145deg,#73f5b8,#159d77)';tone('start')},900+Math.random()*1800);timer(5,()=>finish('draw',0),'استنى')}
function tapRush(area){setText('#challenge-instruction','كل واحد يدوس بأسرع ما عنده لمدة 5 ثواني!');area.innerHTML='<div class="dual-zone"><div class="zone pink" id="tap-h"><div><strong>حمودي</strong><small>دوس هنا</small></div><span class="tap-count">0</span></div><div class="zone blue" id="tap-z"><div><strong>زوزا</strong><small>دوسي هنا</small></div><span class="tap-count">0</span></div></div>';let c={h:0,z:0};['h','z'].forEach(k=>$('#tap-'+k).addEventListener('pointerdown',e=>{e.preventDefault();if(state.roundLocked)return;c[k]++;$('#tap-'+k+' .tap-count').textContent=c[k];tone('click')}));timer(5,()=>finish(c.h===c.z?'draw':c.h>c.z?'h':'z'),'دوسوا!')}
function memory(area){const colors=[['أحمر','#ff4f9a'],['أزرق','#45c7ff'],['أخضر','#72f5b4'],['أصفر','#ffd166'],['بنفسجي','#a78bfa']];const len=4+Math.min(2,Math.floor(state.round/5));const seq=Array.from({length:len},()=>Math.floor(Math.random()*colors.length));setText('#challenge-instruction','احفظوا الترتيب… وبعدها اختاروا نفس السلسلة.');area.innerHTML='<div><div class="memory-seq" id="memory-seq"></div><div class="memory-controls" id="memory-controls"></div></div>';const seqEl=$('#memory-seq');seq.forEach(i=>{const d=document.createElement('div');d.className='memory-chip';d.style.background=colors[i][1];d.textContent=colors[i][0];seqEl.append(d)});later(()=>{seqEl.innerHTML='';const controls=$('#memory-controls');let pick=[];colors.forEach((c,i)=>{const b=document.createElement('button');b.className='choice-btn';b.textContent=c[0];b.onclick=()=>{pick.push(i);b.disabled=true;if(pick.length===seq.length){const ok=pick.every((v,j)=>v===seq[j]);finish(ok?'h':'z',ok?1:0)}};controls.append(b)})},2200);timer(9,()=>finish('draw',0),'ذاكرة')}
function targetHit(area){setText('#challenge-instruction','اصطاد الهدف المتحرك! كل إصابة = نقطة.');area.innerHTML='<div class="target-arena" id="target-arena"></div>';const ar=$('#target-arena'),c={h:0,z:0};for(let i=0;i<10;i++){const t=document.createElement('button');t.className='target';t.setAttribute('aria-label','هدف');t.style.left=Math.random()*88+'%';t.style.top=Math.random()*72+'%';t.addEventListener('pointerdown',()=>{const k=i%2?'z':'h';c[k]++;t.style.left=Math.random()*88+'%';t.style.top=Math.random()*72+'%';tone('correct')});ar.append(t)}timer(7,()=>finish(c.h===c.z?'draw':c.h>c.z?'h':'z'),'اصطاد')}
function colorTrap(area){const words=['أحمر','أزرق','أخضر','أصفر'],cols=['#ff4f9a','#45c7ff','#72f5b4','#ffd166'];const actual=Math.floor(Math.random()*4),written=(actual+1+Math.floor(Math.random()*3))%4;setText('#challenge-instruction','اختار اللون الحقيقي للكلمة، مش المكتوب!');area.innerHTML='<div class="question-box"><div class="color-word" style="color:'+cols[actual]+'">'+words[written]+'</div><div class="choice-grid">'+words.map((w,i)=>'<button class="choice-btn" data-color="'+i+'" style="border-color:'+cols[i]+'">'+w+'</button>').join('')+'</div></div>';$$('[data-color]').forEach(b=>b.onclick=()=>finish(+b.dataset.color===actual?'h':'z',+b.dataset.color===actual?1:0));timer(6,()=>finish('draw',0),'اختار')}
function quickMath(area){const a=5+state.round,b=3+(state.round%5),op=state.round%3===0?'+':state.round%3===1?'×':'−',ans=op==='+'?a+b:op==='×'?a*b:a-b;const opts=[ans,ans+2,ans-3,ans+5].sort(()=>Math.random()-.5);setText('#challenge-instruction','أول إجابة صحيحة تاخد النقطة!');area.innerHTML='<div class="question-box"><h3>'+a+' '+op+' '+b+' = ؟</h3><div class="choice-grid">'+opts.map(v=>'<button class="choice-btn" data-ans="'+v+'">'+v+'</button>').join('')+'</div></div>';$$('[data-ans]').forEach(b=>b.onclick=()=>finish(+b.dataset.ans===ans?'h':'z',+b.dataset.ans===ans?1:0));timer(7,()=>finish('draw',0),'احسب')}
function dodge(area){setText('#challenge-instruction','اختاروا المسار الآمن قبل ما العقبات تنزل!');area.innerHTML='<div class="choice-grid"><button class="choice-btn" data-dodge="h">مسار حمودي<br><small>يسار</small></button><button class="choice-btn" data-dodge="z">مسار زوزا<br><small>يمين</small></button></div>';let safe=Math.random()<.5?'h':'z';$$('[data-dodge]').forEach(b=>b.onclick=()=>finish(b.dataset.dodge===safe?b.dataset.dodge:(b.dataset.dodge==='h'?'z':'h'),b.dataset.dodge===safe?1:0));timer(5,()=>finish('draw',0),'اهربوا')}
function perfectTiming(area){setText('#challenge-instruction','دوس لما المؤشر يكون جوه المنطقة الخضرا!');area.innerHTML='<div><div class="timing-bar"><div class="timing-perfect"></div><div class="timing-needle" id="needle"></div></div><button class="btn btn-primary full" id="timing-btn">دوس في الوقت الصح</button></div>';let pos=0,dir=1;const needle=$('#needle');state.raf=requestAnimationFrame(function loop(){if(state.roundLocked)return;pos+=dir*1.3;if(pos>98||pos<0)dir*=-1;needle.style.left=pos+'%';state.raf=requestAnimationFrame(loop)});$('#timing-btn').onclick=()=>{const good=pos>40&&pos<60;finish(good?'h':'z',good?1:0);if(!good)toast('Miss… ركز أكتر!')};timer(7,()=>finish('draw',0),'توقيت')}
function cards(area){setText('#challenge-instruction','اختار كارت واحد… الحظ هيقول كلمته!');const vals=['+1','+2','+3','×2','-1','سرقة'];area.innerHTML='<div class="card-grid">'+vals.map((v,i)=>'<button class="card-choice" data-card="'+i+'">?</button>').join('')+'</div>';const outcomes=[1,2,3,2,-1,1];$$('[data-card]').forEach(b=>b.onclick=()=>{const v=outcomes[+b.dataset.card];const k=state.round%2?'z':'h';$$('[data-card]').forEach(x=>x.textContent=vals[+x.dataset.card]);finish(k,v>0? 'h'===k?v:0:0,{});if(v<0){state.scores[k]=Math.max(0,state.scores[k]+v);updateScore();}});timer(7,()=>finish('draw',0),'حظ')}
function coupleQuiz(area){const q=questions[Math.floor(Math.random()*questions.length)];setText('#challenge-instruction','كل واحد يختار… مين الإجابة الأقرب؟');area.innerHTML='<div class="question-box"><h3>'+q+'</h3><div class="big-options"><button class="choice-btn" data-q="h">حمودي</button><button class="choice-btn" data-q="z">زوزا</button></div></div>';$$('[data-q]').forEach(b=>b.onclick=()=>{finish(b.dataset.q,1);toast('إجابة حلوة… واثقين؟')});timer(8,()=>finish('draw',0),'اختاروا')}
function trueFalse(area){const statements=['حمودي يقدر يقعد يوم كامل من غير ما يكلم زوزا.','زوزا بتعرف تخبي مفاجأة لآخر لحظة.','حمودي عمره ما بينسى مناسبة مهمة.','زوزا بتكسب أي نقاش بسهولة.'];const s=statements[state.round%statements.length];setText('#challenge-instruction','صح ولا غلط؟ أول إجابة تكسب.');area.innerHTML='<div class="question-box"><h3>“'+s+'”</h3><div class="big-options"><button class="choice-btn" data-tf="صح">صح</button><button class="choice-btn" data-tf="غلط">غلط</button></div></div>';$$('[data-tf]').forEach(b=>b.onclick=()=>finish(b.dataset.tf==='صح'?'h':'z',1));timer(6,()=>finish('draw',0),'جاوب')}
function fastAnswer(area){const odd=Math.floor(Math.random()*5);setText('#challenge-instruction','اختار الشكل المختلف بسرعة!');area.innerHTML='<div class="order-grid">'+[0,1,2,3,4].map(i=>'<button class="order-btn" data-odd="'+i+'">'+(i===odd?'◆':'◇')+'</button>').join('')+'</div>';$$('[data-odd]').forEach(b=>b.onclick=()=>finish(+b.dataset.odd===odd?'h':'z',+b.dataset.odd===odd?1:0));timer(5,()=>finish('draw',0),'ركز')}
function order(area){setText('#challenge-instruction','اضغطوا الأرقام بالترتيب من 1 لـ 5!');let nextN=1;const nums=[1,2,3,4,5].sort(()=>Math.random()-.5);area.innerHTML='<div class="order-grid">'+nums.map(n=>'<button class="order-btn" data-order="'+n+'">'+n+'</button>').join('')+'</div>';$$('[data-order]').forEach(b=>b.onclick=()=>{if(+b.dataset.order===nextN){b.classList.add('done');nextN++;tone('correct');if(nextN===6)finish('h',1)}else{tone('wrong');toast('بالراحة يا نجم… بالترتيب!')}});timer(8,()=>finish('draw',0),'ترتيب')}
function combo(area){setText('#challenge-instruction','اضرب الأهداف وخلّي الكومبو يعلى!');area.innerHTML='<div class="question-box"><div class="combo-meter">COMBO × <span id="combo">0</span></div><button class="combo-target" id="combo-target" aria-label="هدف الكومبو"></button></div>';let combo=0;const t=$('#combo-target');const move=()=>{t.style.transform='translate('+((Math.random()-.5)*170)+'px,'+((Math.random()-.5)*80)+'px)'};t.onclick=()=>{combo++;setText('#combo',combo);state.bestCombo=Math.max(state.bestCombo,combo);tone('correct');move()};timer(8,()=>finish(combo>3?'h':'z',combo>3?1:0),'كومبو')}
function finalBattle(area){setText('#challenge-instruction','دي الجولة اللي ممكن تقلب النتيجة! أول واحد يضغط يكسب +2.');area.innerHTML='<button class="challenge-btn" id="final-btn">جاهزين؟</button>';const b=$('#final-btn');later(()=>{b.textContent='FINAL BATTLE — دوس!';b.style.background='linear-gradient(145deg,#ffd166,#e58d1d)';tone('start');b.onclick=()=>finish(Math.random()<.5?'h':'z',2)},1300);timer(6,()=>finish('draw',0),'النهاية')}
function pause(){if(state.screen!=='game-screen'||state.roundLocked)return;state.paused=true;state.timers.forEach(clearTimeout);state.timers.forEach(clearInterval);if(state.raf)cancelAnimationFrame(state.raf);$('#pause-modal').classList.remove('hidden')}
function resume(){state.paused=false;$('#pause-modal').classList.add('hidden');toast('يلا نكمل!');loadRound();}
function quit(){clearLoops();$('#pause-modal').classList.add('hidden');show('menu-screen')}
function toggleSound(){state.sound=!state.sound;setText('#sound-label',state.sound?'ON':'OFF');setText('#game-sound-label',state.sound?'ON':'OFF');if(state.sound)tone('click')}
$$('[data-action]').forEach(b=>b.addEventListener('click',()=>{const a=b.dataset.action;({start,countdown,next,replay:start,menu:()=>show('menu-screen'),howto:()=>show('howto-screen'),pause,resume,quit,sound:toggleSound}[a]||(()=>{}))()}));
window.addEventListener('keydown',e=>{if(e.key==='Escape'&&state.screen==='game-screen')pause()});
show('menu-screen');
})();
